name = "EytzingerSequences"
uuid = "dd04f2a2-e08c-4620-a7ab-81a37b9c6eaa"
authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
